unit tests with mock i2c
blues/note-python pull request #54
Opened 2023-02-10 00:30 UTC by m-mcgowan

Adds tests over a mock i2c connection. 

The tests are factored into common tests for any transport, plus transport-specific tests. This approach will enable a real I2C or Serial connection to be used with HIL testing.

2023-02-10 13:59 UTC, bsatrom commented on test/test_notecard.py
>  import pytest
Why are you importing `unittest` when `pytest` is already present?

2023-02-10 14:02 UTC, bsatrom commented
@m-mcgowan I'm having a hard time seeing what has actually changed in this pr so I am inclined to reject it until it's either simplified or broken into multiple PRs. Rather than taking on a giant refactor of how the tests work, why not add the I2C mocks and tests and we can worry about a refactor later, if at all?

2023-02-10 17:47 UTC, m-mcgowan commented
I didn't think it was that big a refactor. All I did was factor out the notecard connection from the tests by moving them in to a base class which calls `get_port()` to retrieve the port with an expected response, and this is used by two subclasses, one for i2c and one for serial that defines `get_port()`.  

It's not presently building on github actions because that's a linux environment and the notecard communications code has the I2C setup hard-coded for to be different for that. It worked on my machine because I'm on OSX - I need to change the logic to also use the same in a test environment so that it is consistent regardless of runtime platform.

When we have HIL testing for this, all we have to do is define another class that uses a real I2C/serial connection running the same tests.

2023-02-10 18:38 UTC, m-mcgowan commented on test/test_notecard.py
>  import pytest
`unittest` supports classes of tests, which I use for reuse of common tests and parameterization of these across different environments.

2023-02-10 20:26 UTC, m-mcgowan commented
![](https://github.trello.services/images/mini-trello-icon.png) [mock tests for note-python and I2C](https://trello.com/c/lGskUR4t/11-mock-tests-for-note-python-and-i2c)

2023-02-10 20:35 UTC, haydenroche5 requested changes

2023-02-10 20:35 UTC, haydenroche5 commented on .github/workflows/manual-run.yml
> +        flake8 test/ notecard/ examples/ --count --ignore=E722,F401,F403,W503,E501 --show-source --statistics
Can we add a comment explaining what we're ignoring?

2023-02-10 20:35 UTC, haydenroche5 commented on test/test_notecard.py
> +    def test_debug_mode_on_i2c(self):
The first several lines of this look like what `get_i2c_and_port` does. Can we use that instead?

2023-02-10 20:38 UTC, m-mcgowan commented on .github/workflows/manual-run.yml
> +        flake8 test/ notecard/ examples/ --count --ignore=E722,F401,F403,W503,E501 --show-source --statistics
will do. Ideally the github actions should use the makefile so we DRY this up.

2023-02-10 20:51 UTC, m-mcgowan commented on test/test_notecard.py
> +    def test_debug_mode_on_i2c(self):
Sure. there's definitely more refactoring we could do, I just wanted to do the minimal to get it working.

2023-02-10 22:02 UTC, bsatrom commented on test/test_notecard.py
>  import pytest
What's a way we can do this without adding a second unit testing framework?

2023-02-10 23:07 UTC, m-mcgowan commented
I didn't build this specifically to target HIL, I just wanted to factor out the communications channel, which is orthogonal to most of the tests (i.e. the tests are comms-neutral - they don't care about what channel they are using.) It just happens that with that done, adding HIL later will be easier because we can reuse the same mechanism.

We want a simple way to run all the comms-neutral tests over both mocked serial and i2c, and IMHO this was the simplest way to do it without causing maintenance headaches. The only other way I can think of is to duplicate (copy and paste) all the existing serial tests, and rework them to use i2c, but then we have a lot of duplication of code, which will only become worse when we add more comms channels to the test suite.

2023-02-10 23:29 UTC, m-mcgowan commented on test/test_notecard.py
>  import pytest
just a fyi - `unittest` was already being used for [mocks](https://github.com/blues/note-python/blame/main/test/test_notecard.py#L7) before this PR. 

`unittest` is built into python so we could rework the pytest , which at present are just assertions for raised exceptions. But I wouldn't stop using pytest - it's a great test runner, while `unittest` deals with expressing tests and creating mocks. 

`pytest` is intended to be used with `unittest` - https://docs.pytest.org/en/7.1.x/how-to/unittest.html#:~:text=pytest%20supports%20running%20Python%20unittest,full%20advantage%20of%20pytest's%20features.

I've reworked the test classes so they don't have `unittest.TestCase` as a base class, and pytest is fine with that, so long as the class name starts with `Test`.

2023-02-11 02:52 UTC, bsatrom commented
My apologies @m-mcgowan, the combination of an impenetrable diff and mention of HiL caused me to (wrongly) assume that more was going on here than mocking I2C for testing.

2023-02-11 02:53 UTC, bsatrom commented on test/test_notecard.py
>  import pytest
Ah was it? Shows that it's been too long since I've been in this library.

2023-02-11 02:53 UTC, bsatrom approved these changes

2023-02-11 04:27 UTC, m-mcgowan commented
No problem! I was going to suggest you view the files side-by-side because then it's much easier to see the diff than what github gives you

2023-02-13 18:58 UTC, haydenroche5 approved these changes

2023-02-13 19:56 UTC, merged